In [1]:
import numpy as np

In [2]:
x = np.array([1, 3, 5])

print(x.mean())

3.0


In [3]:
print(x.shape)

(3,)


In [4]:
a = np.array([[1, 2, 3], [2, 3, 4]])
print(a.shape)

(2, 3)


In [5]:
x = np.array([1, 3, 5, 7, 9, 11]).reshape(3, 2)
x

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [6]:
y = np.ones([3, 4])
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
x = np.array([[1, 3, 5], [2, 4, 6]])
print(x[1])
print(x[1].mean())
print(x.mean())
print(x.shape)

[2 4 6]
4.0
3.5
(2, 3)


In [8]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(list1[1][1])

12


In [9]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(list1[:][1])
print(list1[:, 1])

[2, 12]


TypeError: list indices must be integers or slices, not tuple

In [10]:
np_ary = np.array(list1)
print(np_ary[:, 1])

[11 12 13]


In [11]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(np.array(list1[:, 1]))

TypeError: list indices must be integers or slices, not tuple

In [12]:
list1 = np.array([[1, 11], [2, 12], [3, 13]])
print(list1[:, 1])

[11 12 13]


In [13]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(np.array(list1[:][0]))

[ 1 11]


In [14]:
import math

In [15]:
math.sqrt(2)

1.4142135623730951

In [16]:
math.sqrt([2, 3, 4])

TypeError: must be real number, not list

In [17]:
np.sqrt([2, 3, 4])

array([1.41421356, 1.73205081, 2.        ])

In [18]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
print(a[1][1])

6


In [21]:
zero_vector = np.zeros(3)
print(zero_vector)

[0. 0. 0.]


In [22]:
zero_matrix = np.zeros((4, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
zero_vector = np.zeros(5)
zero_vector

array([0., 0., 0., 0., 0.])

In [24]:
zero_matrix = np.zeros((5, 3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
my_array = np.zeros(15).reshape(3, 5)
my_array += 4
my_array

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [26]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = x + y
print(z)

[5 7 9]


In [27]:
z = x * y
print(z)

[ 4 10 18]


In [28]:
s = [1, 2, 3]
t = s + 1
print(t)

TypeError: can only concatenate list (not "int") to list

In [ ]:
s = np.array([1, 2, 3])
t = s + 1
print(t)

In [29]:
x = np.array([4, 8, 12])
y = np.array([2, 4, 6])
z = x / y
print(z)

[2. 2. 2.]


In [30]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(X[1])
print(X[:, 1]) # 각 차원 배열의 1번 인덱스 내용 출력

[4 5 6]
[2 5 8]


In [31]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(X[:, 1] + Y[:, 1]) # 배열 간 계산도 가능

[ 5 11 17]


In [32]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
i = [1, 3, 5]
print(a[i])

[20 40 60]


In [33]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
# COPY 방식에 따른 차이
b = a[1:6:2]
b[1] = 10
print('b:', b)
print('a:', a)
type(b)

b: [20 10 60]
a: [10 20 30 10 50 60 70]


numpy.ndarray

In [34]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = np.array(a[1:6:2])
print('b:', b)
b[1] = 10
print('b:', b)
print('a:', a)
type(b)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 40 50 60 70]


numpy.ndarray

In [35]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = a > 50
print(b)

[False False False False False  True  True]


In [36]:
ary = np.random.random(5) # 0~1 사이 무작위값 생성
print(ary)
print(np.all(ary >= 0.3)) # 괄호 안의 조건을 배열 원소 모두가 만족하는가
print(np.any(ary > 0.7)) # 괄호 안의 조건을 배열 원소 중 하나라도 만족하는가

[0.75482963 0.07525034 0.95063644 0.95905026 0.93385642]
False
True


In [37]:
height = np.array([173, 168, 171, 189, 179])
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = (weight / (height ** 2)) * 10000
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [38]:
height = [173, 168, 171, 189, 179]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
bmi = (weight / np.power(height, 2)) * 10000
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [39]:
print(bmi > 21)

[ True False  True  True  True]


In [40]:
# 등간격 나누기(시작값, 끝값, 간격)
np.linspace(0, 12, 4)

array([ 0.,  4.,  8., 12.])

In [41]:
# retstep: 간격 출력하기
np.linspace(0, 12, 4, retstep=True)

(array([ 0.,  4.,  8., 12.]), 4.0)

In [42]:
np.linspace(0, 12, 3, endpoint=False)

array([0., 4., 8.])

In [43]:
# logspace: 로그 형태 간격
np.logspace(np.log10(10), np.log10(100), 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [44]:
np.logspace(1, 2, 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])